#pragma once

float const PI = 3.14159265f;

// Tausworth parameters
unsigned const TAUSWORTHE_NUM_THREADS             = 256;
unsigned const TAUSWORTHE_NUM_BLOCKS              = 16;
unsigned const TAUSWORTHE_TOTAL_NUM_THREADS       = TAUSWORTHE_NUM_THREADS * TAUSWORTHE_NUM_BLOCKS;
unsigned const TAUSWORTHE_NUM_SEEDS_PER_GENERATOR = 4;
unsigned const TAUSWORTHE_NUM_SEEDS = TAUSWORTHE_NUM_BLOCKS * TAUSWORTHE_NUM_THREADS * TAUSWORTHE_NUM_SEEDS_PER_GENERATOR;
unsigned const TAUSWORTHE_NUM_OUTPUTS_PER_RUN           = 2048;
unsigned const TAUSWORTHE_SEED_SIZE                     = TAUSWORTHE_NUM_THREADS * 4;
unsigned const TAUSWORTHE_TOTAL_SEED_SIZE               = TAUSWORTHE_SEED_SIZE * TAUSWORTHE_NUM_BLOCKS;
unsigned const TAUSWORTHE_NUM_RANDOM_NUMBERS_PER_THREAD = TAUSWORTHE_NUM_OUTPUTS_PER_RUN * 8;
unsigned const TAUSWORTHE_NUM_RANDOM_NUMBERS_PER_BLOCK = TAUSWORTHE_NUM_RANDOM_NUMBERS_PER_THREAD * TAUSWORTHE_NUM_THREADS;
unsigned const TAUSWORTHE_OUTPUT_SIZE = TAUSWORTHE_NUM_RANDOM_NUMBERS_PER_BLOCK * TAUSWORTHE_NUM_BLOCKS;