#ifndef DMT_TRAINING_COOPERATIVE_GROUPS_THE_MACROS_H
#define DMT_TRAINING_COOPERATIVE_GROUPS_THE_MACROS_H

#define ANSI_RED "\033[31m"
#define ANSI_YLW "\033[93m"
#define ANSI_RST "\033[0m"

#endif // DMT_TRAINING_COOPERATIVE_GROUPS_THE_MACROS_H
