<#
.SYNOPSIS
    Apply an environment generated by resetenv.ps1 to the current PowerShell session.

.DESCRIPTION
    This script reads lines of the form KEY=VALUE from stdin (or a file) and sets the corresponding environment variables
    in the current PowerShell session. It deduplicates PATH-like variables automatically.

.USAGE
    # From a pipe
    & .\resetenv.ps1 | .\applyenv.ps1

    # Or from a file
    .\applyenv.ps1 -File "env.txt"
#>

param(
    [string]$File
)

# ----------------------------
# Read environment lines
# ----------------------------
if ($File)
{
    $lines = Get-Content $File
}
elseif ($input)
{
    $lines = $input | ForEach-Object { $_.ToString() }
}
else
{
    Write-Host "[applyenv] No input provided." -ForegroundColor Yellow
    return
}

foreach ($line in $lines)
{
    if (-not $line)
    {
        continue
    }

    if ($line -match "^(?<key>[^=]+)=(?<value>.*)$")
    {
        $key = $matches["key"]
        $value = $matches["value"]

        # Deduplicate PATH-like variables
        if ($key -match "PATH|INCLUDE|LIB|LIBPATH")
        {
            $parts = $value -split ";"
            $seen = @{ }
            $value = ($parts | Where-Object { $_ -and (-not $seen.ContainsKey($_)); $seen[$_] = $true }) -join ";"
        }

        # Apply to current session
        Set-Item -Path "Env:$key" -Value $value
    }
}

Write-Host "[applyenv] Environment applied successfully." -ForegroundColor Green
